repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks
  - repo: local
    hooks:
      - id: semgrep
        name: semgrep
        entry: semgrep
        args: ["--config", "sast/semgrep-rules.yml", "--error"]
        language: system
        files: \.py$
